// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/users": {
    params: {};
  };
  "/orders": {
    params: {};
  };
  "/orders.new": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/users" | "/orders" | "/orders.new";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/users.jsx": {
    id: "routes/users";
    page: "/users";
  };
  "routes/orders.jsx": {
    id: "routes/orders";
    page: "/orders";
  };
  "routes/orders.new.jsx": {
    id: "routes/orders.new";
    page: "/orders.new";
  };
};