"""Added Product model and updated relationships and seed

Revision ID: 84550746c22b
Revises: 6bb8bbe22520
Create Date: 2025-10-04 21:18:46.264018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84550746c22b'
down_revision = '6bb8bbe22520'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'products', ['product_id'], ['id'])
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('quantity')
        batch_op.drop_column('product_id')

    # ### end Alembic commands ###
