"""Added udated_at fields to all models

Revision ID: c6ad7f4a5459
Revises: 84550746c22b
Create Date: 2025-10-05 16:37:05.107744

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6ad7f4a5459'
down_revision = '84550746c22b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
